export default {
    "fr":{
        "data": {
            "name": "MAZEL",
            "firstname": "Axel",
            "telephone": "06.26.80.67.24",
            "age": "25 ans",
            "adress": "7 Rue du Finistère",
            "email": "contact@axelmazel.fr",
            "bio": "",
            "job": "Développeur web",
            "photoLink": "axelmzl.jpg",
            "resumeLink": "./CV.pdf",
            "downloadButton": "Télécharger mon CV",
            "presentation": "J'ai 25 ans et je suis développeur web Junior à Toulouse, vidéaste, designer et concepteur. Actuellement étudiant sur Toulouse à Ynov Informatique en développement informatique et en freelance. Je suis toujours très motivé pour de nouveaux projets !",
            "HtmlImg": "html.png",
            "CssImg": "css.png",
            "JSImg": "javascript.png",
            "PHPImg": "php.png",
            "ReactImg": "react.png",
            "SkillTitle": "Mes compétences",
            "ResumeTitle": "A propos de moi",
            "ChooseButton": "A propos / Mes compétences",
            "Copyright": "Tous droits réservés à la structure Biterroise",
            "FooterButtonTxt": "Voir le vrai site",
            "OriginalWebsiteLink": "https://axelmazel.fr",
            "ExperienceTitle": "Expériences",
            "Experience1": "Freelance",
            "Experience1Desc": "Travail en microentreprise pour le compte d'association, société dans la réalisation de site internet.",
            "Experience1Date": "2015 - 2020",
            "Experience2": "Jingoo",
            "Experience2Desc": "Développement web sous Symfony d'une plateforme dédiée aux photographes",
            "Experience2Date": "2019 - 2020",
        },
        "menu": {
            "home": "Accueil",
            "aboutme": "A Propos",
        }
    }
};